require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'TestUI' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'TestUITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  # post_install do |installer|
  #   react_native_post_install(installer)
  # end
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      if config.name != 'Release'
      # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = 'arm64, arm64e, x86_64' # real devices
      config.build_settings["VALID_ARCHS"] = 'arm64, arm64e, x86_64' # simulator
    end
  end
  end
end